version: "3.7"
services:
  web:
    build: .
    env_file: "nappy.env"
    ports:
      - "4000:4000"
    restart: "always"
  migration:
    build: .
    env_file: "nappy.env"
    depends_on:
      - web
    command: bin/migrate
    restart: "no"
