version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 30
    mem_limit: 500m
    ports:
      - "5432:5432"
    env_file:
      - nappy_dev.env
    volumes:
      - ./priv/repo/nappy_dev.sql:/docker-entrypoint-initdb.d/nappy_dev.sql

  # app:
  #   container_name: nappy
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   cpu_count: 1
  #   cpus: 0.5
  #   cpu_percent: 30
  #   mem_limit: 500m
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - nappy_dev.env
  #   volumes:
  #     - ./_build/prod/rel/nappy/:/app

  minio:
    image: bitnami/minio
    container_name: minio
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 30
    mem_limit: 500m
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - nappy_dev.env
    volumes:
      - ./minio-persistence:/data

  # This is used when deploying to
  # a vps with caddy as web server
  # web:
  #   build: .
  #   env_file: "nappy.env"
  #   ports:
  #     - "4000:4000"
  #   restart: "always"
  # migration:
  #   build: .
  #   env_file: "nappy.env"
  #   depends_on:
  #     - web
  #   command: bin/migrate
  #   restart: "no"
