# fly.toml app configuration file generated for nappy-staging on 2023-05-12T11:02:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nappy-staging"
primary_region = "sea"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "nappy-staging.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
