name: CI

on:
  pull_request:
  push:

jobs:
  check-commit-message:
    name: Check commit message for skipping build(s)
    runs-on: ubuntu-latest
    # skips CI and prints cli message, without fail build badge
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: print message via cli
        run: echo "no need to build, based from commit message"

  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:14
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      minio:
        image: bitnami/minio
        ports: ['9000:9000', '9001:9001']
        env:
          MINIO_ROOT_USER: minio-root-user
          MINIO_ROOT_PASSWORD: minio-root-password
          MINIO_DEFAULT_BUCKETS: test-bucket

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.x'

      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: install linux packages
        run: |
          sudo apt install libvips-dev

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix format --check-formatted

      - name: Compile project
        # run: mix compile --warnings-as-errors
        run: mix compile

      - name: test uploading an image
        run: mix test --trace test/nappy_web/api/upload_images_test.exs

      - name: test sponsored images
        run: mix test --trace test/nappy_web/api/sponsored_images_test.exs

      - name: run static analysis
        run: mix credo --all --strict
